CREATE TABLE ENGINEER(
  ENGINEER_ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL UNIQUE,
  PHONE_NUMBER VARCHAR(15) NOT NULL,
  PASSWORD CHAR(30) NOT NULL
);

CREATE TABLE APPOINTMENT(
  APPOINTMENT_ID BIGSERIAL PRIMARY KEY,
  ENGINEER_ID BIGINT NOT NULL,
  CUSTOMER_NAME VARCHAR(64) NOT NULL,
  CUSTOMER_EMAIL VARCHAR(64) NOT NULL,
  CUSTOMER_ADDRESS VARCHAR(64) NOT NULL,
  CUSTOMER_PHONE_NUMBER VARCHAR(32),
  TIMESLOT VARCHAR(12),
  APPOINTMENT_DATE DATE,
  IS_COMPLETE VARCHAR(5) NOT NULL,
  WORK_DONE VARCHAR(200),
  CHARGE DECIMAL(10)
);

CREATE TABLE HOLIDAY(
  HOLIDAY_ID BIGSERIAL PRIMARY KEY,
  ENGINEER_ID BIGINT NOT NULL,
  HOLIDAY_DATE DATE NOT NULL
);

ALTER TABLE APPOINTMENT ADD FOREIGN KEY (ENGINEER_ID) REFERENCES ENGINEER(ENGINEER_ID);
ALTER TABLE HOLIDAY ADD FOREIGN KEY (ENGINEER_ID) REFERENCES ENGINEER(ENGINEER_ID);